apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

namespace: goargocdapp

images:
- name: goargocdapp
  newName: goargocdapp
  newTag: latest